[package]
name = "cutr"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
regex = "1.10.6"
anyhow = "1.0.89"


[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
pretty_assertions = "1.4.1"
rand = "0.8.5"
